// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Mockservice is a mock of service interface
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// writeSalesReport mocks base method
func (m *Mockservice) writeSalesReport(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "writeSalesReport", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// writeSalesReport indicates an expected call of writeSalesReport
func (mr *MockserviceMockRecorder) writeSalesReport(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "writeSalesReport", reflect.TypeOf((*Mockservice)(nil).writeSalesReport), ctx)
}
